### ISSUE TITLE
Upgrade to ASP.NET Core 1.1

### ISSUE THREAD

**Issue by RehanSaeed** [Azure-Samples/active-directory-dotnet-webapi-getting-started#2]
This should be done accross the board to all the projects.

**Comment by markti** [comment]
@jmprieur is there an up to date sample for asp.net core?

**Comment by jmprieur** [comment]
@markti : 
I would recommend looking at: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2, as explained in the README.md :)

We'll deprecate this sample soon

**Comment by markti** [comment]
That has a wpf client (public client). I'm looking for asp.net core mvc web app that is a confidential app example.

**Comment by jmprieur** [comment]
@markti : I suggest you have a look at this sample for the client: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-1-Call-MSGraph (Web App)

**Comment by jmprieur** [comment]
Archiving this repo
